# Generated by Django 4.0.6 on 2022-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='classImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('enrol_no', models.IntegerField(verbose_name='Enrollment no')),
                ('image_url', models.CharField(max_length=12333)),
                ('prog', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
