# Generated by Django 4.0.6 on 2022-07-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_classimages_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classimages',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='classimages',
            name='image_url',
            field=models.CharField(default='', max_length=12333),
        ),
    ]
